import './globals.css'
import ClientComponent from './ClientComponent'

export const metadata = {
  title: 'Inventory Management LNMIIT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClientComponent>{children}</ClientComponent>
    </html>
  )
}
